### ISSUE TITLE
Grant Emma.Souza@tn.gov access to Workflows in TN

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#2161]
**What needs to be done? Why does it need to be done?**
Please grant Emma.Souza@tn.gov access to District 40 Workflows in TN. It's also fine if they see everyone in the tool with no district restriction.

Here is the Intercom message with the ask:

Good afternoon,

I am receiving this error code when trying to log in to recidiviz. I am the Admin Secretary for District 40, can you please grant me access?

Emma Souza | Admin Secretary
Emma.Souza@tn.gov

**Additional context**
cc @evangreenlowe @ayeshakhawaja (relevant request that admin panel work should help solve in future!)

**Comment by Catacola** [comment]
Added admin secretary role to workflows in https://github.com/Recidiviz/recidiviz-data/pull/14760.

This should be fixed after this afternoon's deploy

**Comment by sychang** [comment]
Just tried to have Emma log in and they said they are still getting the same error - any hypotheses on what's happening?

**Comment by danawillow** [comment]
Cool, I think I know what's happening. Tony's PR was merged on Monday Aug 22, which means it didn't make it to prod until yesterday. Only problem is that the thing that runs after the deploy to update the bigquery views failed, so it never got updated. There _may_ be a way to work around it but I think instead I'm going to try to properly fix it this afternoon because there are other issues with the same root cause.
